djangoProject/djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('taskmanager/', include('taskmanager.urls')),


    path('', include('taskmanager.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProject/taskmanager/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .converters import IntArrayConverter
from django.urls import register_converter

register_converter(IntArrayConverter, 'int_array')

app_name = 'taskmanager'
urlpatterns = [
                  path('tasks/', views.task_list, name='task_list'),
                  path('tasks/create/', views.create_task, name='create_task'),
                  path('tasks/edit/<int:task_id>/', views.edit_task, name='edit_task'),
                  path('tasks/delete/<int:task_id>/', views.delete_task, name='delete_task'),
                  path('signup', views.signup, name='signup'),
                  path('', views.logar, name='logar'),
                  path('tasks/delete/<int_array:ids>/', views.multiple_delete, name='multiple_delete'),
                  path("profile/", views.profile, name='profile'),
                  path("profile/edit_profile/", views.edit_profile, name='edit_profile'),
                  path("sair", views.sair, name='sair'),
                  path("creditos", views.creditos, name='creditos'),
                  path('users/', views.user_list, name='user_list'),
                  path('users/edit/<int:utilizador_id>', views.edit_user, name='edit_user'),
                  path('users/delete/<int:utilizador_id>/', views.delete_user, name='delete_user'),
                  path('tasks/change/<int:task_id>/', views.change_completion, name='change'),
                  path('users/delete/<int_array:ids>/', views.multiple_delete_users, name='multiple_delete_users'),
                  path('users/tasks/<int:utilizador_id>', views.users_tasks, name='users_tasks'),
                  path('users/create', views.criar_user, name='criar_user'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoProject/taskmanager/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

class Task(models.Model):
    PRIORITY_CHOICES = [
        ('pouca', 'Pouca'),
        ('mediana', 'Mediana'),
        ('alta', 'Alta')
    ]

    title = models.CharField(max_length=200)
    description = models.TextField()
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES)
    deadline = models.DateField()
    completed = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Utilizador(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    imagem = models.ImageField(upload_to='profile_pics', blank=True, null=True)
    descricao = models.TextField( max_length=300,default ="Ainda sem descricao, escreva um pouco sobre si!")
    datadecriacao = models.DateField(auto_now_add=True)


    def tarefascriadas(self):
        return Task.objects.filter(user=self.user).count()

    def tarefasadecorrer(self):
        return Task.objects.filter(user=self.user,completed=False).count()

    def tarefasconcluidas(self):
        return Task.objects.filter(user=self.user, completed=True).count()

    def __str__(self):
        return f'{self.user.username} Utilizador'

    isAdmin = models.BooleanField(default=False)

djangoProject/taskmanager/forms.py
# forms.py
from django import forms
from .models import Task, Utilizador


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'priority', 'completed', 'deadline']
        widgets = {
            'deadline': forms.DateInput(attrs={'type': 'date'})
        }




class UtilizadorForm(forms.ModelForm):
    imagem = forms.ImageField(required=False)
    class Meta:
        model = Utilizador
        fields = ['nome','email','descricao','imagem']

class UserForm(forms.ModelForm):
    class Meta:
        model = Utilizador
        exclude = ['datadecriacao']
        fields = ['nome', 'email', 'descricao','isAdmin', 'imagem', 'datadecriacao']
        widgets = {
            'datadecriacao': forms.DateInput(attrs={'type': 'date', 'readonly': 'readonly'})
        }

djangoProject/taskmanager/views.py
# views.py
from django.core.paginator import Paginator
from django.shortcuts import redirect
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .models import Task, Utilizador
from .forms import TaskForm, UtilizadorForm, UserForm



@login_required(login_url='/taskmanager/')
def task_list(request):
    items = Task.objects.filter(user=request.user)
    items_per_page = 5
    paginator = Paginator(items, items_per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'taskmanager/task_list.html', context)


@login_required(login_url='/taskmanager/')
def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.user = request.user
            task.save()
            return redirect('taskmanager:task_list')
    else:
        form = TaskForm()
    return render(request, 'taskmanager/create_task.html', {'form': form})


@login_required(login_url='/taskmanager/')
def edit_task(request, task_id):
    task = Task.objects.get(id=task_id)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('taskmanager:task_list')
    else:
        form = TaskForm(instance=task)
    return render(request, 'taskmanager/edit_task.html', {'form': form, 'task': task})


@login_required(login_url='/taskmanager/')
def change_completion(request, task_id):
    task = Task.objects.get(id=task_id)
    if task.completed:
        task.completed="False"
    else:
        task.completed="True"
    task.save()
    return HttpResponseRedirect(reverse('taskmanager:task_list'))

@login_required(login_url='/taskmanager/')
def delete_task(request, task_id):
    task = Task.objects.get(id=task_id)
    task.delete()
    return redirect('taskmanager:task_list')


def signup(request):
    if (request.method == 'POST'):
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        nome = request.POST['nome']
        isAdmin = request.POST.get('isAdmin', False)
        if(isAdmin=="on"):
            isAdmin=True
        else:
            isAdmin=False
        u = User.objects.create_user(username, email, password)
        user = Utilizador(user=u, email=email, nome=nome, isAdmin=isAdmin)
        user.save()
        login(request, u)
        return HttpResponseRedirect(reverse('taskmanager:task_list'))
    else:
        return render(request, 'taskmanager/signup.html')


def logar(request):
    if (request.method == 'POST'):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('taskmanager:task_list'))
        else:
            context = {
                'error_message': "Informação de login incorreta"
            }
            print(context)
            return render(request, 'taskmanager/login.html', context)

    else:
        return render(request, 'taskmanager/login.html')

@login_required(login_url='/taskmanager/')
def multiple_delete(request, ids):
    for id in ids:
        task = Task.objects.get(id=id)
        task.delete()
    return HttpResponseRedirect(reverse('taskmanager:task_list'))


@login_required(login_url='/taskmanager/')
def profile(request):
    return render(request, 'taskmanager/profile.html')


@login_required(login_url='/taskmanager/')
def edit_profile(request):
    profile = request.user.utilizador
    if request.method == 'POST':
        form = UtilizadorForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('taskmanager:profile')
    else:
        form = UtilizadorForm(instance=profile)
    return render(request, 'taskmanager/edit_profile.html', {'form': form})



@login_required(login_url='/taskmanager/')
def sair(request):
    request.session.flush
    logout(request)
    return HttpResponseRedirect(reverse('taskmanager:logar'))



@login_required(login_url='/taskmanager/')
def user_list(request):
    items = Utilizador.objects.all()
    items_per_page = 5
    paginator = Paginator(items, items_per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'taskmanager/user_list.html', context)


@login_required(login_url='/taskmanager/')
def edit_user(request, utilizador_id):
    utilizador = Utilizador.objects.get(id=utilizador_id)
    if request.method == 'POST':
        form = UserForm(request.POST, instance=utilizador)
        if form.is_valid():
            form.save()
            return redirect('taskmanager:user_list')
    else:
        form = UserForm(instance=utilizador)
    return render(request, 'taskmanager/edit_user.html', {'form': form, 'utilizador': utilizador})

@login_required(login_url='/taskmanager/')
def delete_user(request, utilizador_id):
    utilizador = Utilizador.objects.get(pk=utilizador_id)
    utilizador.delete()
    return redirect('taskmanager:user_list')

@login_required(login_url='/taskmanager/')
def multiple_delete_users(request, ids):
    for id in ids:
        utilizador = Utilizador.objects.get(id=id)
        utilizador.delete()
    return HttpResponseRedirect(reverse('taskmanager:user_list'))


def creditos(request):
    return render(request, 'taskmanager/creditos.html')

@login_required(login_url='/taskmanager/')
def users_tasks(request, utilizador_id):
    user = User.objects.get(id=utilizador_id)
    items = Task.objects.filter(user=user)
    items_per_page = 5
    paginator = Paginator(items, items_per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'taskmanager/task_list.html', context)

def criar_user(request):
    if (request.method == 'POST'):
        username = request.POST['username']
        password = request.POST['password']
        email = request.POST['email']
        nome = request.POST['nome']
        isAdmin = request.POST.get('isAdmin', False)
        if(isAdmin=="on"):
            isAdmin=True
        else:
            isAdmin=False
        u = User.objects.create_user(username, email, password)
        user = Utilizador(user=u, email=email, nome=nome, isAdmin=isAdmin)
        user.save()

        return HttpResponseRedirect(reverse('taskmanager:user_list'))
    else:
        return render(request, 'taskmanager/criar_user.html')

djangoProject/taskmanager/templates/taskmanager/Creditos.html
{% extends "./base.html" %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'taskmanager/css/mystyle.css'%}">
    <title> Créditos </title>
{% endblock %}

{% block content %}
<div class="creditos">
    <div class="proposito">
    <h2>Proposito do Projeto</h2>
        <p>O objetivo deste website é providenciar aos seus utilizadores uma<br>
    plataforma para gerirem as suas tarefas de uma forma simples e<br>
    eficiente. O tema será minimalista e moderno, com um foco no uso<br>
    fácil e funcionalidade.<br></p>

        </div>
    <div class="funcionalidades">
    <h2>Principais Funcionalidades</h2>

<ul id="list">
<li>Registo de users e login: Users podem registar uma conta e<br>
fazer login na mesma para aceder às suas tarefas.
</li>
 <br>
<li>Criação de Tarefas e a sua gestão: Users podem criar novas<br>
tarefas, definir prioridades e deadlines, e marcar tarefas<br>
como completadas. Também podem editar e apagar as suas<br>
próprias tarefas.

</li>
 <br>
<li>Filtração de tarefas e sua organização: Users podem filtrar as<br>
suas tarefas por prioridade, deadline e status de cumprimento.<br>
Também podem organizá-las por vários critérios.

</li>
  <br>
<li>Painel Admin: Admins podem ver e gerir todas as tarefas e<br>
users no website, incluindo criar novas tarefas e editar as<br>
informações dos users.
</li>
</ul>

    </div>
    <div class="criadores">
    <h2>Criadores:</h2>

<table class ="tablecred" border="1">
<tr>
<th>Nome</th>
<th>Turma</th>
<th>Numero</th>
</tr>
<tr>
<td>Joao Franco</td>
<td>LEI-C6</td>
    <td>98975</td>
<td><img src="{% static 'taskmanager/images/JoaoFranco.jpg' %}" alt="JoaoFranco" style="width:90px;height:90px;"></td>
</tr>
<tr>
<td>Tiago Castro</td>
<td>LEI-C5</td>
<td>92905</td>
<td><img src="{% static 'taskmanager/images/TiagoCastro.jpg' %}" alt="TiagoCastro" style="width:90px;height:90px;"></td>
</tr>
<tr>
<td>Douglas Lino</td>
<td>LEI-C5</td>
<td>98850</td>
<td><img src="{% static 'taskmanager/images/DouglasLino.jpg' %}" alt="DouglasLino" style="width:90px;height:90px;"></td>
</tr>
</table>
        </div>

</div>

 {% endblock %}

djangoProject/taskmanager/templates/taskmanager/base.html
<!DOCTYPE html>
<html lang="pt">
    {% block head %}
<head>
    <meta charset="UTF-8">
    {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'taskmanager/css/mystyle.css'%}">
</head>
        {% endblock %}
<body>
     {% if request.user.is_authenticated %}
    <header>

    <nav class = "topo">
            <a href="https://www.iscte-iul.pt/"><img src="https://upload.wikimedia.org/wikipedia/commons/0/04/Logo_ISCTE_Instituto_Universit%C3%A1rio_de_Lisboa.svg" alt="ISCTE" style="width:80px;height:15px;"></a>

            <a class = "hcontainters" href="{% url 'taskmanager:profile' %}">O meu perfil</a>

            <a class = "hcontainters" href="{% url 'taskmanager:task_list' %}">Suas Tasks</a>

            <a class = "hcontainters" href="{% url 'taskmanager:creditos' %}">Creditos</a>
        {% if request.user.utilizador.isAdmin %}

            <a class = "hcontainters" href="{% url 'taskmanager:user_list' %}">Users</a>
            {% endif %}

            <a class = "hcontainters" href="{% url 'taskmanager:sair' %}">Sair</a>
        </nav>
    {% else %}
        <nav class = "topo">
            <a href="https://www.iscte-iul.pt/"><img src="https://upload.wikimedia.org/wikipedia/commons/0/04/Logo_ISCTE_Instituto_Universit%C3%A1rio_de_Lisboa.svg" alt="ISCTE" style="width:80px;height:15px;"></a>

            <a class = "hcontainters" href="{% url 'taskmanager:logar' %}"> Login </a>&nbsp;

            <a class = "hcontainters" href="{% url 'taskmanager:signup' %}"> Signup </a>&nbsp;

            <a class = "hcontainters" href="{% url 'taskmanager:creditos' %}"> Creditos </a>
        </nav>
    {% endif %}
    </header>
    {% block content %}
    {% endblock %}


    {% block options %}
    {% endblock %}
</body>
</html>

djangoProject/taskmanager/templates/taskmanager/create_task.html
{% extends "./base.html" %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'taskmanager/css/mystyle.css'%}">
    <title> Criar Tarefa </title>
{% endblock %}

{% block content %}
  <h2>Criar tarefa</h2>
  <form method="post" action="{% url 'taskmanager:create_task' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
  </form>
{% endblock %}

djangoProject/taskmanager/templates/taskmanager/criar_user.html
{% extends "./base.html" %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'taskmanager/css/mystyle.css'%}">
    <title> Registo </title>
{% endblock %}


{% block content %}
<div class="login">
    <h1> Registo</h1>

        <form action="{% url 'taskmanager:criar_user'%}"  method="post">
        {% csrf_token %}
            <input type="text" name="username" placeholder="Username">
            <br>
            <br>
            <input type="text" name="email" placeholder="Email">
            <br>
            <br>
            <input type="text" name="nome" placeholder="Nome">
            <br>
            <br>
            <input type="password" name="password" placeholder="Senha">
            <br>
            <br>
            <label for="my-checkbox">Administrador: </label>
            <input type="checkbox" id="my-checkbox" name="isAdmin">
            <br>
            <br>
            <input type="submit" class ="Eliminaruser" value="Criar" />
            <br>
            <br>
        </form>
    </div>
{% endblock %}

djangoProject/taskmanager/templates/taskmanager/edit_profile.html
{% extends "./base.html" %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'taskmanager/css/mystyle.css'%}">
    <title> Editar Perfil </title>
{% endblock %}

{% block content %}
    <div class="editprofile">

  <h2>Alterar Perfil</h2>
  <form class="epcontainters" method="POST" action="{% url 'taskmanager:edit_profile' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Imagem: {{ form.imagem  }}</p>
      <br>
    <p >Nome:  {{ form.nome }}</p>
      <br>Descricao:
   <p> {{ form.descricao }}</p>
      <br>
   <p>  Email: {{ form.email }}</p>
      <br>
    <button onclick="history.back()" type="submit">Salvar mudancas</button>
</form>
<p></p>
    <button onclick="history.back()" >Cancelar</button>

    </div>

{% endblock %}

djangoProject/taskmanager/templates/taskmanager/edit_task.html
{% extends "./base.html" %}

{% block head %}
    {% load static %}
    <script type="text/javascript" src="{% static 'taskmanager/javascript/confirm.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'taskmanager/css/mystyle.css'%}">
    <title> Editar Tarefa </title>
{% endblock %}

{% block content %}
    <div class="edittask">
  <h2>Editar tarefa</h2>
  <form method="post" action="{% url 'taskmanager:edit_task' task.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
  </form>
<p></p>
    <button id="delete" onclick="confirmTask()">Eliminar</button>
    </div>
{% endblock %}

djangoProject/taskmanager/templates/taskmanager/edit_user.html
{% extends "./base.html" %}

{% block head %}
    {% load static %}
    <script type="text/javascript" src="{% static 'taskmanager/javascript/confirm.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'taskmanager/css/mystyle.css'%}">

    <title> Editar Utilizador </title>
{% endblock %}

{% block content %}
<div class="editprofile">
  <h2>Editar utilizador</h2>
    <a href="{% url 'taskmanager:users_tasks' utilizador.id %}">Tarefas de {{ utilizador.nome }}</a>
  <form method="post" class="epcontainers" action="{% url 'taskmanager:edit_user' utilizador.id %}">
    {% csrf_token %}
    {{ form.as_p }}
      <label> Data de criação: {{ utilizador.datadecriacao }}  </label><p></p>
    <button type="submit">Atualizar</button>
  </form>
    <p></p>
    <button id="delete" onclick="confirmUser()">Eliminar</button>
</div>
{% endblock %}

djangoProject/taskmanager/templates/taskmanager/login.html
{% extends "./base.html" %}

{% block head %}
    {% load static %}
    <script type="text/javascript" src="{% static 'taskmanager/javascript/error.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'taskmanager/css/mystyle.css'%}">
    <script>
    var errorMessage = "{{ error_message }}";
        window.onload = error(errorMessage);
    </script>
    <title> Autenticação </title>
{% endblock %}

{% block content %}
        <div class="login">
    <header> <h2>Login </h2> </header>

            <form action="{% url 'taskmanager:logar' %}"  method="post">
            {% csrf_token %}
            <input type="text" name="username" placeholder="Username">
            <input type="password" name="password" placeholder="Senha">
                <p></p>
            <input type="submit"  class ="Eliminaruser" value="Login" />
            </form>


    <h2> Não tem uma conta? Crie uma <a href="{% url 'taskmanager:signup' %}">aqui</a></h2>
     </div>
{% endblock %}

djangoProject/taskmanager/templates/taskmanager/profile.html
{% extends "./base.html" %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'taskmanager/css/mystyle.css'%}">
    <title> Perfil </title>
{% endblock %}

{% block content %}

    <div class="perfilPrincipal">


        <div class="Informacaopessoal">
        {% if user.utilizador.imagem %}
    <h2><img class="imagens" src="{{ request.user.utilizador.imagem.url }}" alt="{{ request.user.utilizador.nome }}'s profile picture" width="200" height="200"></h2>
        {% else %}
    <h2><img src="{% static 'taskmanager/images/default-user-image.png' %}" width="200" height="200"></h2>
{% endif %}
    <h3 > {{ request.user.utilizador.nome }} </h3>
    <h4 >{{request.user.username}}</h4>
    <p  >Sobre si: {{request.user.utilizador.descricao}}</p>
    <p >Email: {{request.user.utilizador.email}}</p>
    <p></p>

    <button onclick="window.location='edit_profile/';">Alterar Informacoes</button>

        </div>

    <br></br>
    <br></br>

    <div class="estatisticas">

    <h3>Estatisticas</h3>
    <p>Criacao da Conta : {{ request.user.utilizador.datadecriacao }}</p>
    <p>Tarefas Criadas : {{ request.user.utilizador.tarefascriadas}}</p>
    <p>Tarefas a Decorrer : {{ request.user.utilizador.tarefasadecorrer }}</p>
    <p>Tarefas Concluidas : {{ request.user.utilizador.tarefasconcluidas }}</p>
        </div>

    </div>

{% endblock %}

djangoProject/taskmanager/templates/taskmanager/signup.html
{% extends "./base.html" %}

{% block head %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'taskmanager/css/mystyle.css'%}">
    <title> Registo </title>
{% endblock %}


{% block content %}
<div class="login">
    <h1> Registo</h1>

        <form action="{% url 'taskmanager:signup'%}"  method="post">
        {% csrf_token %}
            <input type="text" name="username" placeholder="Username" required>
            <br>
            <br>
            <input type="text" name="email" placeholder="Email" required>
            <br>
            <br>
            <input type="text" name="nome" placeholder="Nome" required>
            <br>
            <br>
            <input type="password" name="password" placeholder="Senha" required>
            <br>
            <br>
            <label for="my-checkbox">Administrador: </label>
            <input type="checkbox" id="my-checkbox" name="isAdmin">
            <br>
            <br>
            <input type="submit" class ="Eliminaruser" value="Criar" />
            <br>
            <br>
        </form>
    </div>
{% endblock %}

djangoProject/taskmanager/templates/taskmanager/task_list.html
{% extends "./base.html" %}
{% block head %}
    {% load static %}
    <script type="text/javascript" src="{% static 'taskmanager/javascript/tasks.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'taskmanager/css/mystyle.css'%}">
    <title> Lista de Tarefas </title>
    
{% endblock %}
{% block content %}
  <div class="Task">
  <h2 style="color: black">&nbsp;&nbsp;&nbsp;&nbsp;Task List</h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'taskmanager:create_task' %}" class="Createuser">Create Task</a>&nbsp;
    <input type="text" placeholder="Pesquisar" id="search" onkeyup="search()">
    <select id="criteria">
        <option selected value="title"> Título</option>
        <option value="priority"> Prioridade</option>
        <option value="completion"> Estado </option>
        <option value="deadline"> Data </option>
    </select>
      <div style="top: 97px; position:absolute; left: 433px">
    <img onclick="sort()" src="{% static 'taskmanager/images/sorting_arrow.png' %}" width="25" height="25">
    <label id="sort"> </label>
      </div>
    <ul id="list">
  {% if page_obj %}
    {% for task in page_obj %}
      <li>
      <input type="checkbox" id="{{ task.id }}" name="ids" onchange="visibility()">
      <a href="{% url 'taskmanager:edit_task' task.id %}"> {{ task.title }}</a>
      <label class="priority" style="color: black"> || Priority: {{ task.priority }} || </label>
      <label class="deadline" style="color: black"> Due Date: </label>
          <label class="deadline" style="color: black">{{ task.deadline }}</label>
      <label class="deadline" style="color: black"> || </label>
      <label style="color: black"> Completion status: </label>
      <input type="checkbox" class="completed" {% if task.completed %} checked="true" {% endif %} onchange="update({{ task.id }})">
      </li>
    {% endfor %}
  {% else %}
        <p>Não há tarefas disponíveis.</p>
    {% endif %}
      </ul>
    <button id="deleteAll" type="button" onclick="select()" style="display: none;">Eliminar</button>
        <p></p>
    <button id="deleteAll" type="button" onclick="select()" style="display: none;" class="Eliminaruser">Eliminar</button>

    <div class="paginationtask">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; primeira</a>
            <a href="?page={{ page_obj.previous_page_number }}">anterior</a>
        {% endif %}

        <span class="current-page">
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">próxima</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">última &raquo;</a>
        {% endif %}
    </span>
    </div>
</div>
{% endblock %}

djangoProject/taskmanager/templates/taskmanager/user_list.html
{% extends "./base.html" %}
{% block head %}
    {% load static %}
    <script type="text/javascript" src="{% static 'taskmanager/javascript/users.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'taskmanager/css/mystyle.css'%}">
    <title> Lista de Utilizadores </title>
{% endblock %}

{% block content %}
    <div class="user">
  <h2 style="color: black">&nbsp;&nbsp;&nbsp;&nbsp;User List</h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="{% url 'taskmanager:criar_user' %}" class="Createuser">Create User</a>&nbsp;
    <input type="text" placeholder="Pesquisar" id="search" onkeyup="search()">

    <div style="top: -31px; position:relative; left: 350px">
    <img onclick="sort()" src="{% static 'taskmanager/images/sorting_arrow.png' %}" width="25" height="25">

    <label id="sort"> </label></div>
    <div style="top: -20px; position: relative">
    <ul id="list">
  {% if page_obj %}
    {% for utilizador in page_obj %}
      <li>
      <input type="checkbox" id="{{ utilizador.id }}" name="ids" onchange="visibility()">
      <a href="{% url 'taskmanager:edit_user' utilizador.id %}"> {{ utilizador.nome }}</a>

      </li>
    {% endfor %}
  {% else %}
        <p>Não há Users disponíveis.</p>
    {% endif %}
    <p></p>
    <button id="deleteAll" type="button" onclick="select()" style="display: none;" class="Eliminaruser">Eliminar</button>
  </ul>
    </div>

<div class="paginationuser">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; primeira</a>
            <a href="?page={{ page_obj.previous_page_number }}">anterior</a>
        {% endif %}

        <span class="current-page">
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">próxima</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">última &raquo;</a>
        {% endif %}
    </span>
</div>
        </div>
{% endblock %}